### ISSUE TITLE
About performance.

### ISSUE THREAD

**Issue by zhaohui-yang** [ricky40403/DSQ#1]
Hi, thanks for sharing this great implementation. I wonder if you have ever evaluated the module you wrote, does it performs same with the paper's performance?

**Comment by ricky40403** [comment]
Sorry for the late replying, it has not been verified because I am a bit busy. I will try to find time to run some experiments. Thanks.

**Comment by zhaohui-yang** [comment]
Thanks, bro.

**Comment by ricky40403** [comment]
It had been tested in 4 bit with res18 on imagenet, it seems that the top1 is similar to the paper's result.
